import React from 'react';
import Products from "@/Components/Home/Products";

export const metadata = {
    title: "All Products",
    description: "Generated by create next app",
};

const ProductsPage = () => {
    return (
        <div>
            <Products></Products>
        </div>
    );
};

export default ProductsPage;